#!/bin/bash
set -evu

# single argument = root directory of module to test

MYPYPATH=$1

ROOT_INIT_FILE=$(python -c "from importlib.util import find_spec; print(find_spec('pytket').origin)")

# remove pytket root init file
mv "$ROOT_INIT_FILE" "$ROOT_INIT_FILE.ignore"

set +e
mypy --config-file=mypy.ini --no-incremental -p pytket -p tests
STATUS=$?
set -e

# reset init file
mv "$ROOT_INIT_FILE.ignore" "$ROOT_INIT_FILE"

exit $STATUS
