name: Build and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'wheel/**'
      - 'runci/**'
      - ae/testsegf
  release:
    types:
      - created
      - edited
  schedule:
    # 04:00 every Tuesday morning
    - cron: '0 4 * * 2'

jobs:
  checks:
    name: Build and test
    strategy:
      matrix:
        os: ['ubuntu-22.04', 'macos-12', 'windows-2022']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Build and test including remote checks (3.10) mypy
      if:  (matrix.os == 'macos-12') && ((github.event_name == 'pull_request' &&  github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'release' || contains(github.ref, 'refs/heads/wheel') || github.event_name == 'schedule')
      shell: bash
      run: |
        ./.github/workflows/build-test mypy
    - name: Build and test including remote checks (3.10) nomypy
      if:  (matrix.os != 'macos-12') && (github.event_name == 'push' || (github.event_name == 'pull_request' &&  github.event.pull_request.head.repo.full_name == github.repository) || github.event_name == 'release' || github.event_name == 'schedule')
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
    - name: Set up Python 3.11
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build and test (3.11)
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
    - name: Set up Python 3.12
      if: github.event_name == 'push' || github.event_name == 'schedule'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Build and test (3.12)
      if: github.event_name == 'push' || github.event_name == 'schedule'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
